package com.example.anuviya.compiler.symbol;

/**
 * Stable, unique symbol identifiers generated by the compiler.
 */
public record SymbolId(long uniqueId) {
    public static final SymbolId NONE = new SymbolId(-1);
}
